-- Legacy syntax groups + Treesitter `@*` captures.
---@param p table
return function(p)
  local s = p.syntax
  return {
    -- legacy vim syntax
    Comment = { fg = s.comment, italic = true },
    Constant = { fg = s.constant },
    String = { fg = s.string },
    Character = { fg = s.string },
    Number = { fg = s.number },
    Boolean = { fg = s.number },
    Float = { fg = s.number },
    Identifier = { fg = p.fg.text },
    Function = { fg = s.func },
    Statement = { fg = s.keyword },
    Keyword = { fg = s.keyword },
    Conditional = { fg = s.keyword },
    Repeat = { fg = s.keyword },
    Operator = { fg = s.operator },
    Type = { fg = s.type },
    StorageClass = { fg = s.keyword },
    Structure = { fg = s.type },
    PreProc = { fg = s.namespace },
    Include = { fg = s.keyword },
    Special = { fg = s.escape },
    SpecialChar = { fg = s.escape },
    Delimiter = { fg = s.punctuation },
    Tag = { fg = s.tag },
    Todo = { fg = p.bg.base, bg = p.accent.base, bold = true },
    Error = { fg = p.semantic.error_text },

    -- treesitter
    ['@comment'] = { link = 'Comment' },
    ['@keyword'] = { fg = s.keyword },
    ['@keyword.function'] = { fg = s.keyword },
    ['@keyword.return'] = { fg = s.keyword },
    ['@keyword.operator'] = { fg = s.keyword },
    ['@function'] = { fg = s.func },
    ['@function.call'] = { fg = s.func },
    ['@function.builtin'] = { fg = s.func },
    ['@function.method'] = { fg = s.func },
    ['@constructor'] = { fg = s.type },
    ['@type'] = { fg = s.type },
    ['@type.builtin'] = { fg = s.type },
    ['@module'] = { fg = s.namespace },
    ['@namespace'] = { fg = s.namespace },
    ['@string'] = { fg = s.string },
    ['@string.regexp'] = { fg = s.regexp },
    ['@string.escape'] = { fg = s.escape },
    ['@string.special'] = { fg = s.escape },
    ['@character'] = { fg = s.string },
    ['@number'] = { fg = s.number },
    ['@boolean'] = { fg = s.number },
    ['@constant'] = { fg = s.constant },
    ['@constant.builtin'] = { fg = s.number },
    ['@constant.macro'] = { fg = s.constant },
    ['@variable'] = { fg = p.fg.text },
    ['@variable.builtin'] = { fg = s.namespace },
    ['@variable.parameter'] = { fg = s.parameter },
    ['@variable.member'] = { fg = s.variable },
    ['@property'] = { fg = s.variable },
    ['@operator'] = { fg = s.operator },
    ['@punctuation'] = { fg = s.punctuation },
    ['@punctuation.bracket'] = { fg = s.punctuation },
    ['@punctuation.delimiter'] = { fg = s.punctuation },
    ['@punctuation.special'] = { fg = s.escape },
    ['@attribute'] = { fg = s.decorator }, -- decorators (@foo)
    ['@tag'] = { fg = s.tag },
    ['@tag.attribute'] = { fg = s.attribute },
    ['@tag.delimiter'] = { fg = s.punctuation },
    ['@markup.heading'] = { fg = s.func, bold = true },
    ['@markup.link'] = { fg = s.constant, underline = true },
    ['@markup.raw'] = { fg = s.string },
  }
end
