// Read palette.<mode>.json (built from Radix) and generate every target via typed
// builders (scripts/targets.ts). `--check` verifies generated files are up to date.

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Palette } from './build-palette.ts';
import { vscode, wezterm, ghostty } from './targets.ts';

const ROOT = path.resolve(import.meta.dir, '..');
const MODES = ['dark', 'light'] as const;
type Mode = (typeof MODES)[number];

// ── JSON palette -> Lua table ──
function toLua(value: unknown, indent = 1): string {
  const pad = '  '.repeat(indent);
  if (typeof value === 'string') return `'${value}'`;
  if (typeof value !== 'object' || value === null) return String(value);
  const entries = Object.entries(value as Record<string, unknown>)
    .map(([k, v]) => `${pad}${/^[a-zA-Z_]\w*$/.test(k) ? k : `['${k}']`} = ${toLua(v, indent + 1)},`)
    .join('\n');
  return `{\n${entries}\n${'  '.repeat(indent - 1)}}`;
}
function paletteLua(p: Palette): string {
  return `-- GENERATED by scripts/generate.ts from palette.${p.variant}.json -- do not edit.\nreturn ${toLua(p)}\n`;
}

function readPalette(mode: Mode): Palette {
  return JSON.parse(fs.readFileSync(path.join(ROOT, `palette.${mode}.json`), 'utf8')) as Palette;
}

// sRGB hex -> CSS Display-P3 (VS Code supports `color(display-p3 r g b)` in themes).
function hexToP3(hex: string): string {
  const h = hex.replace('#', '');
  const f = (i: number) => (parseInt(h.slice(i, i + 2), 16) / 255).toFixed(4);
  return `color(display-p3 ${f(0)} ${f(2)} ${f(4)})`;
}
function p3ify<T>(v: T): T {
  if (typeof v === 'string') return (/^#[0-9a-fA-F]{6}$/.test(v) ? hexToP3(v) : v) as T;
  if (Array.isArray(v)) return v.map(p3ify) as T;
  if (v && typeof v === 'object') {
    const o: Record<string, unknown> = {};
    for (const [k, val] of Object.entries(v)) o[k] = p3ify(val);
    return o as T;
  }
  return v;
}

const check = process.argv.includes('--check');
const stale: string[] = [];

function emit(rel: string, contents: string) {
  const abs = path.join(ROOT, rel);
  if (check) {
    const cur = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : '';
    if (cur !== contents) stale.push(rel);
    return;
  }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, contents);
  console.log(`generated ${rel}`);
}

for (const mode of MODES) {
  const p = readPalette(mode);
  emit(`lua/interfere/palette_${mode}.lua`, paletteLua(p));
  emit(`editors/vscode/themes/interfere-${mode}-color-theme.json`, vscode(p));
  emit(`terminals/wezterm/interfere-${mode}.toml`, wezterm(p));
  emit(`terminals/ghostty/interfere-${mode}`, ghostty(p));

  // P3 "vibrant" VS Code variant (wide-gamut displays).
  const p3 = p3ify(p);
  p3.name = `${p.name} Vibrant`;
  emit(`editors/vscode/themes/interfere-${mode}-vibrant-color-theme.json`, vscode(p3));
}

// VS Code extension manifest (unscoped name + publisher; the scoped npm package
// can't be a VS Code extension). Generated so version/themes track the source.
const rootPkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')) as { version: string; description: string; license: string };
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const themes = MODES.flatMap((m) => {
  const uiTheme = m === 'dark' ? 'vs-dark' : 'vs';
  return [
    { label: `Interfere ${cap(m)}`, uiTheme, path: `./themes/interfere-${m}-color-theme.json` },
    { label: `Interfere ${cap(m)} Vibrant`, uiTheme, path: `./themes/interfere-${m}-vibrant-color-theme.json` },
  ];
});
const manifest = {
  name: 'interfere-theme',
  displayName: 'Interfere',
  description: rootPkg.description,
  version: rootPkg.version,
  publisher: 'interfere', // TODO: set to your VS Code Marketplace publisher id
  license: rootPkg.license,
  engines: { vscode: '^1.70.0' },
  categories: ['Themes'],
  keywords: ['theme', 'color-theme', 'dark', 'light', 'radix'],
  repository: { type: 'git', url: 'https://github.com/interfere/theme' },
  galleryBanner: { color: readPalette('dark').bg.base, theme: 'dark' },
  contributes: { themes },
};
emit('editors/vscode/package.json', JSON.stringify(manifest, null, 2) + '\n');

if (check) {
  if (stale.length) {
    console.error('Out of date (run `bun run build`):\n  ' + stale.join('\n  '));
    process.exit(1);
  }
  console.log('All generated files up to date.');
}
